/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as idFactoryAccessManagerSol from "./IdFactoryAccessManager.sol";
export * as trexPlatformControllerSol from "./TREXPlatformController.sol";
