/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ITREXToken } from "./ITREXToken";
export type { TREXPlatformController } from "./TREXPlatformController";
