/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface TREXPlatformControllerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "buy"
      | "getTokenInfo"
      | "owner"
      | "pause"
      | "paused"
      | "paymentToken"
      | "quoteBuy"
      | "quoteRedeem"
      | "redeem"
      | "renounceOwnership"
      | "setPaymentToken"
      | "setPrice"
      | "tokenPrice"
      | "transferOwnership"
      | "unpause"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "OwnershipTransferred"
      | "Paused"
      | "PaymentTokenUpdated"
      | "TokenPriceUpdated"
      | "TokensPurchased"
      | "TokensRedeemed"
      | "Unpaused"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "buy",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenInfo",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "paymentToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "quoteBuy",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "quoteRedeem",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "redeem",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setPaymentToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setPrice",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "tokenPrice",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;

  decodeFunctionResult(functionFragment: "buy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTokenInfo",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "paymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "quoteBuy", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "quoteRedeem",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "redeem", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setPaymentToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setPrice", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "tokenPrice", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PaymentTokenUpdatedEvent {
  export type InputTuple = [
    oldPaymentToken: AddressLike,
    newPaymentToken: AddressLike
  ];
  export type OutputTuple = [oldPaymentToken: string, newPaymentToken: string];
  export interface OutputObject {
    oldPaymentToken: string;
    newPaymentToken: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenPriceUpdatedEvent {
  export type InputTuple = [
    token: AddressLike,
    oldPrice: BigNumberish,
    newPrice: BigNumberish
  ];
  export type OutputTuple = [token: string, oldPrice: bigint, newPrice: bigint];
  export interface OutputObject {
    token: string;
    oldPrice: bigint;
    newPrice: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensPurchasedEvent {
  export type InputTuple = [
    investor: AddressLike,
    token: AddressLike,
    issuer: AddressLike,
    tokenAmount: BigNumberish,
    paymentAmount: BigNumberish,
    pricePerToken: BigNumberish
  ];
  export type OutputTuple = [
    investor: string,
    token: string,
    issuer: string,
    tokenAmount: bigint,
    paymentAmount: bigint,
    pricePerToken: bigint
  ];
  export interface OutputObject {
    investor: string;
    token: string;
    issuer: string;
    tokenAmount: bigint;
    paymentAmount: bigint;
    pricePerToken: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensRedeemedEvent {
  export type InputTuple = [
    investor: AddressLike,
    token: AddressLike,
    issuer: AddressLike,
    tokenAmount: BigNumberish,
    paymentAmount: BigNumberish,
    pricePerToken: BigNumberish
  ];
  export type OutputTuple = [
    investor: string,
    token: string,
    issuer: string,
    tokenAmount: bigint,
    paymentAmount: bigint,
    pricePerToken: bigint
  ];
  export interface OutputObject {
    investor: string;
    token: string;
    issuer: string;
    tokenAmount: bigint;
    paymentAmount: bigint;
    pricePerToken: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [account: AddressLike];
  export type OutputTuple = [account: string];
  export interface OutputObject {
    account: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface TREXPlatformController extends BaseContract {
  connect(runner?: ContractRunner | null): TREXPlatformController;
  waitForDeployment(): Promise<this>;

  interface: TREXPlatformControllerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  buy: TypedContractMethod<
    [token: AddressLike, tokenAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getTokenInfo: TypedContractMethod<
    [token: AddressLike],
    [
      [string, bigint, bigint, boolean] & {
        issuer: string;
        tokenDecimals: bigint;
        price: bigint;
        controllerIsAgent: boolean;
      }
    ],
    "view"
  >;

  owner: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  paymentToken: TypedContractMethod<[], [string], "view">;

  quoteBuy: TypedContractMethod<
    [token: AddressLike, tokenAmount: BigNumberish],
    [
      [bigint, bigint, bigint, string] & {
        paymentAmount: bigint;
        price: bigint;
        tokenDecimals: bigint;
        issuer: string;
      }
    ],
    "view"
  >;

  quoteRedeem: TypedContractMethod<
    [token: AddressLike, tokenAmount: BigNumberish],
    [
      [bigint, bigint, bigint, string] & {
        paymentAmount: bigint;
        price: bigint;
        tokenDecimals: bigint;
        issuer: string;
      }
    ],
    "view"
  >;

  redeem: TypedContractMethod<
    [token: AddressLike, tokenAmount: BigNumberish],
    [void],
    "nonpayable"
  >;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setPaymentToken: TypedContractMethod<
    [newPaymentToken: AddressLike],
    [void],
    "nonpayable"
  >;

  setPrice: TypedContractMethod<
    [token: AddressLike, newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;

  tokenPrice: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "buy"
  ): TypedContractMethod<
    [token: AddressLike, tokenAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getTokenInfo"
  ): TypedContractMethod<
    [token: AddressLike],
    [
      [string, bigint, bigint, boolean] & {
        issuer: string;
        tokenDecimals: bigint;
        price: bigint;
        controllerIsAgent: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "paymentToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "quoteBuy"
  ): TypedContractMethod<
    [token: AddressLike, tokenAmount: BigNumberish],
    [
      [bigint, bigint, bigint, string] & {
        paymentAmount: bigint;
        price: bigint;
        tokenDecimals: bigint;
        issuer: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "quoteRedeem"
  ): TypedContractMethod<
    [token: AddressLike, tokenAmount: BigNumberish],
    [
      [bigint, bigint, bigint, string] & {
        paymentAmount: bigint;
        price: bigint;
        tokenDecimals: bigint;
        issuer: string;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "redeem"
  ): TypedContractMethod<
    [token: AddressLike, tokenAmount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPaymentToken"
  ): TypedContractMethod<[newPaymentToken: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setPrice"
  ): TypedContractMethod<
    [token: AddressLike, newPrice: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "tokenPrice"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "PaymentTokenUpdated"
  ): TypedContractEvent<
    PaymentTokenUpdatedEvent.InputTuple,
    PaymentTokenUpdatedEvent.OutputTuple,
    PaymentTokenUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TokenPriceUpdated"
  ): TypedContractEvent<
    TokenPriceUpdatedEvent.InputTuple,
    TokenPriceUpdatedEvent.OutputTuple,
    TokenPriceUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TokensPurchased"
  ): TypedContractEvent<
    TokensPurchasedEvent.InputTuple,
    TokensPurchasedEvent.OutputTuple,
    TokensPurchasedEvent.OutputObject
  >;
  getEvent(
    key: "TokensRedeemed"
  ): TypedContractEvent<
    TokensRedeemedEvent.InputTuple,
    TokensRedeemedEvent.OutputTuple,
    TokensRedeemedEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;

  filters: {
    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "PaymentTokenUpdated(address,address)": TypedContractEvent<
      PaymentTokenUpdatedEvent.InputTuple,
      PaymentTokenUpdatedEvent.OutputTuple,
      PaymentTokenUpdatedEvent.OutputObject
    >;
    PaymentTokenUpdated: TypedContractEvent<
      PaymentTokenUpdatedEvent.InputTuple,
      PaymentTokenUpdatedEvent.OutputTuple,
      PaymentTokenUpdatedEvent.OutputObject
    >;

    "TokenPriceUpdated(address,uint256,uint256)": TypedContractEvent<
      TokenPriceUpdatedEvent.InputTuple,
      TokenPriceUpdatedEvent.OutputTuple,
      TokenPriceUpdatedEvent.OutputObject
    >;
    TokenPriceUpdated: TypedContractEvent<
      TokenPriceUpdatedEvent.InputTuple,
      TokenPriceUpdatedEvent.OutputTuple,
      TokenPriceUpdatedEvent.OutputObject
    >;

    "TokensPurchased(address,address,address,uint256,uint256,uint256)": TypedContractEvent<
      TokensPurchasedEvent.InputTuple,
      TokensPurchasedEvent.OutputTuple,
      TokensPurchasedEvent.OutputObject
    >;
    TokensPurchased: TypedContractEvent<
      TokensPurchasedEvent.InputTuple,
      TokensPurchasedEvent.OutputTuple,
      TokensPurchasedEvent.OutputObject
    >;

    "TokensRedeemed(address,address,address,uint256,uint256,uint256)": TypedContractEvent<
      TokensRedeemedEvent.InputTuple,
      TokensRedeemedEvent.OutputTuple,
      TokensRedeemedEvent.OutputObject
    >;
    TokensRedeemed: TypedContractEvent<
      TokensRedeemedEvent.InputTuple,
      TokensRedeemedEvent.OutputTuple,
      TokensRedeemedEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
  };
}
