/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../../common";

export interface IModularComplianceInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addModule"
      | "bindToken"
      | "callModuleFunction"
      | "canTransfer"
      | "created"
      | "destroyed"
      | "getModules"
      | "getTokenBound"
      | "isModuleBound"
      | "removeModule"
      | "transferred"
      | "unbindToken"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ModuleAdded"
      | "ModuleInteraction"
      | "ModuleRemoved"
      | "TokenBound"
      | "TokenUnbound"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addModule",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "bindToken",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "callModuleFunction",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "canTransfer",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "created",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "destroyed",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getModules",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "getTokenBound",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isModuleBound",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "removeModule",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferred",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unbindToken",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "addModule", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "bindToken", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "callModuleFunction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "created", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "destroyed", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "getModules", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "getTokenBound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isModuleBound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeModule",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferred",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unbindToken",
    data: BytesLike
  ): Result;
}

export namespace ModuleAddedEvent {
  export type InputTuple = [_module: AddressLike];
  export type OutputTuple = [_module: string];
  export interface OutputObject {
    _module: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ModuleInteractionEvent {
  export type InputTuple = [target: AddressLike, selector: BytesLike];
  export type OutputTuple = [target: string, selector: string];
  export interface OutputObject {
    target: string;
    selector: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ModuleRemovedEvent {
  export type InputTuple = [_module: AddressLike];
  export type OutputTuple = [_module: string];
  export interface OutputObject {
    _module: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenBoundEvent {
  export type InputTuple = [_token: AddressLike];
  export type OutputTuple = [_token: string];
  export interface OutputObject {
    _token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenUnboundEvent {
  export type InputTuple = [_token: AddressLike];
  export type OutputTuple = [_token: string];
  export interface OutputObject {
    _token: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IModularCompliance extends BaseContract {
  connect(runner?: ContractRunner | null): IModularCompliance;
  waitForDeployment(): Promise<this>;

  interface: IModularComplianceInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addModule: TypedContractMethod<[_module: AddressLike], [void], "nonpayable">;

  bindToken: TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;

  callModuleFunction: TypedContractMethod<
    [callData: BytesLike, _module: AddressLike],
    [void],
    "nonpayable"
  >;

  canTransfer: TypedContractMethod<
    [_from: AddressLike, _to: AddressLike, _amount: BigNumberish],
    [boolean],
    "view"
  >;

  created: TypedContractMethod<
    [_to: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  destroyed: TypedContractMethod<
    [_from: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getModules: TypedContractMethod<[], [string[]], "view">;

  getTokenBound: TypedContractMethod<[], [string], "view">;

  isModuleBound: TypedContractMethod<[_module: AddressLike], [boolean], "view">;

  removeModule: TypedContractMethod<
    [_module: AddressLike],
    [void],
    "nonpayable"
  >;

  transferred: TypedContractMethod<
    [_from: AddressLike, _to: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  unbindToken: TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addModule"
  ): TypedContractMethod<[_module: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "bindToken"
  ): TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "callModuleFunction"
  ): TypedContractMethod<
    [callData: BytesLike, _module: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "canTransfer"
  ): TypedContractMethod<
    [_from: AddressLike, _to: AddressLike, _amount: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "created"
  ): TypedContractMethod<
    [_to: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "destroyed"
  ): TypedContractMethod<
    [_from: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getModules"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "getTokenBound"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isModuleBound"
  ): TypedContractMethod<[_module: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "removeModule"
  ): TypedContractMethod<[_module: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "transferred"
  ): TypedContractMethod<
    [_from: AddressLike, _to: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unbindToken"
  ): TypedContractMethod<[_token: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ModuleAdded"
  ): TypedContractEvent<
    ModuleAddedEvent.InputTuple,
    ModuleAddedEvent.OutputTuple,
    ModuleAddedEvent.OutputObject
  >;
  getEvent(
    key: "ModuleInteraction"
  ): TypedContractEvent<
    ModuleInteractionEvent.InputTuple,
    ModuleInteractionEvent.OutputTuple,
    ModuleInteractionEvent.OutputObject
  >;
  getEvent(
    key: "ModuleRemoved"
  ): TypedContractEvent<
    ModuleRemovedEvent.InputTuple,
    ModuleRemovedEvent.OutputTuple,
    ModuleRemovedEvent.OutputObject
  >;
  getEvent(
    key: "TokenBound"
  ): TypedContractEvent<
    TokenBoundEvent.InputTuple,
    TokenBoundEvent.OutputTuple,
    TokenBoundEvent.OutputObject
  >;
  getEvent(
    key: "TokenUnbound"
  ): TypedContractEvent<
    TokenUnboundEvent.InputTuple,
    TokenUnboundEvent.OutputTuple,
    TokenUnboundEvent.OutputObject
  >;

  filters: {
    "ModuleAdded(address)": TypedContractEvent<
      ModuleAddedEvent.InputTuple,
      ModuleAddedEvent.OutputTuple,
      ModuleAddedEvent.OutputObject
    >;
    ModuleAdded: TypedContractEvent<
      ModuleAddedEvent.InputTuple,
      ModuleAddedEvent.OutputTuple,
      ModuleAddedEvent.OutputObject
    >;

    "ModuleInteraction(address,bytes4)": TypedContractEvent<
      ModuleInteractionEvent.InputTuple,
      ModuleInteractionEvent.OutputTuple,
      ModuleInteractionEvent.OutputObject
    >;
    ModuleInteraction: TypedContractEvent<
      ModuleInteractionEvent.InputTuple,
      ModuleInteractionEvent.OutputTuple,
      ModuleInteractionEvent.OutputObject
    >;

    "ModuleRemoved(address)": TypedContractEvent<
      ModuleRemovedEvent.InputTuple,
      ModuleRemovedEvent.OutputTuple,
      ModuleRemovedEvent.OutputObject
    >;
    ModuleRemoved: TypedContractEvent<
      ModuleRemovedEvent.InputTuple,
      ModuleRemovedEvent.OutputTuple,
      ModuleRemovedEvent.OutputObject
    >;

    "TokenBound(address)": TypedContractEvent<
      TokenBoundEvent.InputTuple,
      TokenBoundEvent.OutputTuple,
      TokenBoundEvent.OutputObject
    >;
    TokenBound: TypedContractEvent<
      TokenBoundEvent.InputTuple,
      TokenBoundEvent.OutputTuple,
      TokenBoundEvent.OutputObject
    >;

    "TokenUnbound(address)": TypedContractEvent<
      TokenUnboundEvent.InputTuple,
      TokenUnboundEvent.OutputTuple,
      TokenUnboundEvent.OutputObject
    >;
    TokenUnbound: TypedContractEvent<
      TokenUnboundEvent.InputTuple,
      TokenUnboundEvent.OutputTuple,
      TokenUnboundEvent.OutputObject
    >;
  };
}
