/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../common";

export interface ITokenInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "allowance"
      | "approve"
      | "balanceOf"
      | "batchBurn"
      | "batchForcedTransfer"
      | "batchFreezePartialTokens"
      | "batchMint"
      | "batchSetAddressFrozen"
      | "batchTransfer"
      | "batchUnfreezePartialTokens"
      | "burn"
      | "compliance"
      | "decimals"
      | "forcedTransfer"
      | "freezePartialTokens"
      | "getFrozenTokens"
      | "identityRegistry"
      | "isFrozen"
      | "mint"
      | "name"
      | "onchainID"
      | "pause"
      | "paused"
      | "recoveryAddress"
      | "setAddressFrozen"
      | "setCompliance"
      | "setIdentityRegistry"
      | "setName"
      | "setOnchainID"
      | "setSymbol"
      | "symbol"
      | "totalSupply"
      | "transfer"
      | "transferFrom"
      | "unfreezePartialTokens"
      | "unpause"
      | "version"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "AddressFrozen"
      | "Approval"
      | "ComplianceAdded"
      | "IdentityRegistryAdded"
      | "Paused"
      | "RecoverySuccess"
      | "TokensFrozen"
      | "TokensUnfrozen"
      | "Transfer"
      | "Unpaused"
      | "UpdatedTokenInformation"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "allowance",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "approve",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "balanceOf",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "batchBurn",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchForcedTransfer",
    values: [AddressLike[], AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchFreezePartialTokens",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchMint",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchSetAddressFrozen",
    values: [AddressLike[], boolean[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchTransfer",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "batchUnfreezePartialTokens",
    values: [AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "burn",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "compliance",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "decimals", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "forcedTransfer",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "freezePartialTokens",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "getFrozenTokens",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "identityRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "isFrozen",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "mint",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(functionFragment: "onchainID", values?: undefined): string;
  encodeFunctionData(functionFragment: "pause", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "recoveryAddress",
    values: [AddressLike, AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setAddressFrozen",
    values: [AddressLike, boolean]
  ): string;
  encodeFunctionData(
    functionFragment: "setCompliance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setIdentityRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "setName", values: [string]): string;
  encodeFunctionData(
    functionFragment: "setOnchainID",
    values: [AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "setSymbol", values: [string]): string;
  encodeFunctionData(functionFragment: "symbol", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "totalSupply",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transfer",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "transferFrom",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unfreezePartialTokens",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "unpause", values?: undefined): string;
  encodeFunctionData(functionFragment: "version", values?: undefined): string;

  decodeFunctionResult(functionFragment: "allowance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "approve", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "balanceOf", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "batchBurn", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "batchForcedTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchFreezePartialTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "batchMint", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "batchSetAddressFrozen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchUnfreezePartialTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "burn", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "compliance", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "decimals", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "forcedTransfer",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "freezePartialTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getFrozenTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "identityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isFrozen", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "mint", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "onchainID", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "pause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "recoveryAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setAddressFrozen",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setCompliance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setIdentityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setName", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setOnchainID",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "setSymbol", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "symbol", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalSupply",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "transfer", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "transferFrom",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unfreezePartialTokens",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "unpause", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "version", data: BytesLike): Result;
}

export namespace AddressFrozenEvent {
  export type InputTuple = [
    _userAddress: AddressLike,
    _isFrozen: boolean,
    _owner: AddressLike
  ];
  export type OutputTuple = [
    _userAddress: string,
    _isFrozen: boolean,
    _owner: string
  ];
  export interface OutputObject {
    _userAddress: string;
    _isFrozen: boolean;
    _owner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ApprovalEvent {
  export type InputTuple = [
    owner: AddressLike,
    spender: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [owner: string, spender: string, value: bigint];
  export interface OutputObject {
    owner: string;
    spender: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComplianceAddedEvent {
  export type InputTuple = [_compliance: AddressLike];
  export type OutputTuple = [_compliance: string];
  export interface OutputObject {
    _compliance: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdentityRegistryAddedEvent {
  export type InputTuple = [_identityRegistry: AddressLike];
  export type OutputTuple = [_identityRegistry: string];
  export interface OutputObject {
    _identityRegistry: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace PausedEvent {
  export type InputTuple = [_userAddress: AddressLike];
  export type OutputTuple = [_userAddress: string];
  export interface OutputObject {
    _userAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RecoverySuccessEvent {
  export type InputTuple = [
    _lostWallet: AddressLike,
    _newWallet: AddressLike,
    _investorOnchainID: AddressLike
  ];
  export type OutputTuple = [
    _lostWallet: string,
    _newWallet: string,
    _investorOnchainID: string
  ];
  export interface OutputObject {
    _lostWallet: string;
    _newWallet: string;
    _investorOnchainID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensFrozenEvent {
  export type InputTuple = [_userAddress: AddressLike, _amount: BigNumberish];
  export type OutputTuple = [_userAddress: string, _amount: bigint];
  export interface OutputObject {
    _userAddress: string;
    _amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokensUnfrozenEvent {
  export type InputTuple = [_userAddress: AddressLike, _amount: BigNumberish];
  export type OutputTuple = [_userAddress: string, _amount: bigint];
  export interface OutputObject {
    _userAddress: string;
    _amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TransferEvent {
  export type InputTuple = [
    from: AddressLike,
    to: AddressLike,
    value: BigNumberish
  ];
  export type OutputTuple = [from: string, to: string, value: bigint];
  export interface OutputObject {
    from: string;
    to: string;
    value: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UnpausedEvent {
  export type InputTuple = [_userAddress: AddressLike];
  export type OutputTuple = [_userAddress: string];
  export interface OutputObject {
    _userAddress: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace UpdatedTokenInformationEvent {
  export type InputTuple = [
    _newName: string,
    _newSymbol: string,
    _newDecimals: BigNumberish,
    _newVersion: string,
    _newOnchainID: AddressLike
  ];
  export type OutputTuple = [
    _newName: string,
    _newSymbol: string,
    _newDecimals: bigint,
    _newVersion: string,
    _newOnchainID: string
  ];
  export interface OutputObject {
    _newName: string;
    _newSymbol: string;
    _newDecimals: bigint;
    _newVersion: string;
    _newOnchainID: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IToken extends BaseContract {
  connect(runner?: ContractRunner | null): IToken;
  waitForDeployment(): Promise<this>;

  interface: ITokenInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  allowance: TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;

  approve: TypedContractMethod<
    [spender: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  balanceOf: TypedContractMethod<[account: AddressLike], [bigint], "view">;

  batchBurn: TypedContractMethod<
    [_userAddresses: AddressLike[], _amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  batchForcedTransfer: TypedContractMethod<
    [
      _fromList: AddressLike[],
      _toList: AddressLike[],
      _amounts: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  batchFreezePartialTokens: TypedContractMethod<
    [_userAddresses: AddressLike[], _amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  batchMint: TypedContractMethod<
    [_toList: AddressLike[], _amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  batchSetAddressFrozen: TypedContractMethod<
    [_userAddresses: AddressLike[], _freeze: boolean[]],
    [void],
    "nonpayable"
  >;

  batchTransfer: TypedContractMethod<
    [_toList: AddressLike[], _amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  batchUnfreezePartialTokens: TypedContractMethod<
    [_userAddresses: AddressLike[], _amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  burn: TypedContractMethod<
    [_userAddress: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  compliance: TypedContractMethod<[], [string], "view">;

  decimals: TypedContractMethod<[], [bigint], "view">;

  forcedTransfer: TypedContractMethod<
    [_from: AddressLike, _to: AddressLike, _amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  freezePartialTokens: TypedContractMethod<
    [_userAddress: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  getFrozenTokens: TypedContractMethod<
    [_userAddress: AddressLike],
    [bigint],
    "view"
  >;

  identityRegistry: TypedContractMethod<[], [string], "view">;

  isFrozen: TypedContractMethod<[_userAddress: AddressLike], [boolean], "view">;

  mint: TypedContractMethod<
    [_to: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  name: TypedContractMethod<[], [string], "view">;

  onchainID: TypedContractMethod<[], [string], "view">;

  pause: TypedContractMethod<[], [void], "nonpayable">;

  paused: TypedContractMethod<[], [boolean], "view">;

  recoveryAddress: TypedContractMethod<
    [
      _lostWallet: AddressLike,
      _newWallet: AddressLike,
      _investorOnchainID: AddressLike
    ],
    [boolean],
    "nonpayable"
  >;

  setAddressFrozen: TypedContractMethod<
    [_userAddress: AddressLike, _freeze: boolean],
    [void],
    "nonpayable"
  >;

  setCompliance: TypedContractMethod<
    [_compliance: AddressLike],
    [void],
    "nonpayable"
  >;

  setIdentityRegistry: TypedContractMethod<
    [_identityRegistry: AddressLike],
    [void],
    "nonpayable"
  >;

  setName: TypedContractMethod<[_name: string], [void], "nonpayable">;

  setOnchainID: TypedContractMethod<
    [_onchainID: AddressLike],
    [void],
    "nonpayable"
  >;

  setSymbol: TypedContractMethod<[_symbol: string], [void], "nonpayable">;

  symbol: TypedContractMethod<[], [string], "view">;

  totalSupply: TypedContractMethod<[], [bigint], "view">;

  transfer: TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  transferFrom: TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;

  unfreezePartialTokens: TypedContractMethod<
    [_userAddress: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  unpause: TypedContractMethod<[], [void], "nonpayable">;

  version: TypedContractMethod<[], [string], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "allowance"
  ): TypedContractMethod<
    [owner: AddressLike, spender: AddressLike],
    [bigint],
    "view"
  >;
  getFunction(
    nameOrSignature: "approve"
  ): TypedContractMethod<
    [spender: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "balanceOf"
  ): TypedContractMethod<[account: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "batchBurn"
  ): TypedContractMethod<
    [_userAddresses: AddressLike[], _amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchForcedTransfer"
  ): TypedContractMethod<
    [
      _fromList: AddressLike[],
      _toList: AddressLike[],
      _amounts: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchFreezePartialTokens"
  ): TypedContractMethod<
    [_userAddresses: AddressLike[], _amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchMint"
  ): TypedContractMethod<
    [_toList: AddressLike[], _amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchSetAddressFrozen"
  ): TypedContractMethod<
    [_userAddresses: AddressLike[], _freeze: boolean[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchTransfer"
  ): TypedContractMethod<
    [_toList: AddressLike[], _amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "batchUnfreezePartialTokens"
  ): TypedContractMethod<
    [_userAddresses: AddressLike[], _amounts: BigNumberish[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "burn"
  ): TypedContractMethod<
    [_userAddress: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "compliance"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "decimals"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "forcedTransfer"
  ): TypedContractMethod<
    [_from: AddressLike, _to: AddressLike, _amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "freezePartialTokens"
  ): TypedContractMethod<
    [_userAddress: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getFrozenTokens"
  ): TypedContractMethod<[_userAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "identityRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "isFrozen"
  ): TypedContractMethod<[_userAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "mint"
  ): TypedContractMethod<
    [_to: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "onchainID"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "paused"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "recoveryAddress"
  ): TypedContractMethod<
    [
      _lostWallet: AddressLike,
      _newWallet: AddressLike,
      _investorOnchainID: AddressLike
    ],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setAddressFrozen"
  ): TypedContractMethod<
    [_userAddress: AddressLike, _freeze: boolean],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setCompliance"
  ): TypedContractMethod<[_compliance: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setIdentityRegistry"
  ): TypedContractMethod<
    [_identityRegistry: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setName"
  ): TypedContractMethod<[_name: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setOnchainID"
  ): TypedContractMethod<[_onchainID: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setSymbol"
  ): TypedContractMethod<[_symbol: string], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "symbol"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalSupply"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transfer"
  ): TypedContractMethod<
    [to: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferFrom"
  ): TypedContractMethod<
    [from: AddressLike, to: AddressLike, amount: BigNumberish],
    [boolean],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unfreezePartialTokens"
  ): TypedContractMethod<
    [_userAddress: AddressLike, _amount: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "unpause"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "version"
  ): TypedContractMethod<[], [string], "view">;

  getEvent(
    key: "AddressFrozen"
  ): TypedContractEvent<
    AddressFrozenEvent.InputTuple,
    AddressFrozenEvent.OutputTuple,
    AddressFrozenEvent.OutputObject
  >;
  getEvent(
    key: "Approval"
  ): TypedContractEvent<
    ApprovalEvent.InputTuple,
    ApprovalEvent.OutputTuple,
    ApprovalEvent.OutputObject
  >;
  getEvent(
    key: "ComplianceAdded"
  ): TypedContractEvent<
    ComplianceAddedEvent.InputTuple,
    ComplianceAddedEvent.OutputTuple,
    ComplianceAddedEvent.OutputObject
  >;
  getEvent(
    key: "IdentityRegistryAdded"
  ): TypedContractEvent<
    IdentityRegistryAddedEvent.InputTuple,
    IdentityRegistryAddedEvent.OutputTuple,
    IdentityRegistryAddedEvent.OutputObject
  >;
  getEvent(
    key: "Paused"
  ): TypedContractEvent<
    PausedEvent.InputTuple,
    PausedEvent.OutputTuple,
    PausedEvent.OutputObject
  >;
  getEvent(
    key: "RecoverySuccess"
  ): TypedContractEvent<
    RecoverySuccessEvent.InputTuple,
    RecoverySuccessEvent.OutputTuple,
    RecoverySuccessEvent.OutputObject
  >;
  getEvent(
    key: "TokensFrozen"
  ): TypedContractEvent<
    TokensFrozenEvent.InputTuple,
    TokensFrozenEvent.OutputTuple,
    TokensFrozenEvent.OutputObject
  >;
  getEvent(
    key: "TokensUnfrozen"
  ): TypedContractEvent<
    TokensUnfrozenEvent.InputTuple,
    TokensUnfrozenEvent.OutputTuple,
    TokensUnfrozenEvent.OutputObject
  >;
  getEvent(
    key: "Transfer"
  ): TypedContractEvent<
    TransferEvent.InputTuple,
    TransferEvent.OutputTuple,
    TransferEvent.OutputObject
  >;
  getEvent(
    key: "Unpaused"
  ): TypedContractEvent<
    UnpausedEvent.InputTuple,
    UnpausedEvent.OutputTuple,
    UnpausedEvent.OutputObject
  >;
  getEvent(
    key: "UpdatedTokenInformation"
  ): TypedContractEvent<
    UpdatedTokenInformationEvent.InputTuple,
    UpdatedTokenInformationEvent.OutputTuple,
    UpdatedTokenInformationEvent.OutputObject
  >;

  filters: {
    "AddressFrozen(address,bool,address)": TypedContractEvent<
      AddressFrozenEvent.InputTuple,
      AddressFrozenEvent.OutputTuple,
      AddressFrozenEvent.OutputObject
    >;
    AddressFrozen: TypedContractEvent<
      AddressFrozenEvent.InputTuple,
      AddressFrozenEvent.OutputTuple,
      AddressFrozenEvent.OutputObject
    >;

    "Approval(address,address,uint256)": TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;
    Approval: TypedContractEvent<
      ApprovalEvent.InputTuple,
      ApprovalEvent.OutputTuple,
      ApprovalEvent.OutputObject
    >;

    "ComplianceAdded(address)": TypedContractEvent<
      ComplianceAddedEvent.InputTuple,
      ComplianceAddedEvent.OutputTuple,
      ComplianceAddedEvent.OutputObject
    >;
    ComplianceAdded: TypedContractEvent<
      ComplianceAddedEvent.InputTuple,
      ComplianceAddedEvent.OutputTuple,
      ComplianceAddedEvent.OutputObject
    >;

    "IdentityRegistryAdded(address)": TypedContractEvent<
      IdentityRegistryAddedEvent.InputTuple,
      IdentityRegistryAddedEvent.OutputTuple,
      IdentityRegistryAddedEvent.OutputObject
    >;
    IdentityRegistryAdded: TypedContractEvent<
      IdentityRegistryAddedEvent.InputTuple,
      IdentityRegistryAddedEvent.OutputTuple,
      IdentityRegistryAddedEvent.OutputObject
    >;

    "Paused(address)": TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;
    Paused: TypedContractEvent<
      PausedEvent.InputTuple,
      PausedEvent.OutputTuple,
      PausedEvent.OutputObject
    >;

    "RecoverySuccess(address,address,address)": TypedContractEvent<
      RecoverySuccessEvent.InputTuple,
      RecoverySuccessEvent.OutputTuple,
      RecoverySuccessEvent.OutputObject
    >;
    RecoverySuccess: TypedContractEvent<
      RecoverySuccessEvent.InputTuple,
      RecoverySuccessEvent.OutputTuple,
      RecoverySuccessEvent.OutputObject
    >;

    "TokensFrozen(address,uint256)": TypedContractEvent<
      TokensFrozenEvent.InputTuple,
      TokensFrozenEvent.OutputTuple,
      TokensFrozenEvent.OutputObject
    >;
    TokensFrozen: TypedContractEvent<
      TokensFrozenEvent.InputTuple,
      TokensFrozenEvent.OutputTuple,
      TokensFrozenEvent.OutputObject
    >;

    "TokensUnfrozen(address,uint256)": TypedContractEvent<
      TokensUnfrozenEvent.InputTuple,
      TokensUnfrozenEvent.OutputTuple,
      TokensUnfrozenEvent.OutputObject
    >;
    TokensUnfrozen: TypedContractEvent<
      TokensUnfrozenEvent.InputTuple,
      TokensUnfrozenEvent.OutputTuple,
      TokensUnfrozenEvent.OutputObject
    >;

    "Transfer(address,address,uint256)": TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;
    Transfer: TypedContractEvent<
      TransferEvent.InputTuple,
      TransferEvent.OutputTuple,
      TransferEvent.OutputObject
    >;

    "Unpaused(address)": TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;
    Unpaused: TypedContractEvent<
      UnpausedEvent.InputTuple,
      UnpausedEvent.OutputTuple,
      UnpausedEvent.OutputObject
    >;

    "UpdatedTokenInformation(string,string,uint8,string,address)": TypedContractEvent<
      UpdatedTokenInformationEvent.InputTuple,
      UpdatedTokenInformationEvent.OutputTuple,
      UpdatedTokenInformationEvent.OutputObject
    >;
    UpdatedTokenInformation: TypedContractEvent<
      UpdatedTokenInformationEvent.InputTuple,
      UpdatedTokenInformationEvent.OutputTuple,
      UpdatedTokenInformationEvent.OutputObject
    >;
  };
}
