/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IClaimTopicsRegistry,
  IClaimTopicsRegistryInterface,
} from "../../../../../../@erc3643org/erc-3643/contracts/registry/interface/IClaimTopicsRegistry";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "claimTopic",
        type: "uint256",
      },
    ],
    name: "ClaimTopicAdded",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "uint256",
        name: "claimTopic",
        type: "uint256",
      },
    ],
    name: "ClaimTopicRemoved",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_claimTopic",
        type: "uint256",
      },
    ],
    name: "addClaimTopic",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getClaimTopics",
    outputs: [
      {
        internalType: "uint256[]",
        name: "",
        type: "uint256[]",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "_claimTopic",
        type: "uint256",
      },
    ],
    name: "removeClaimTopic",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IClaimTopicsRegistry__factory {
  static readonly abi = _abi;
  static createInterface(): IClaimTopicsRegistryInterface {
    return new Interface(_abi) as IClaimTopicsRegistryInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IClaimTopicsRegistry {
    return new Contract(
      address,
      _abi,
      runner
    ) as unknown as IClaimTopicsRegistry;
  }
}
