/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../../common";

export interface IIdentityRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "batchRegisterIdentity"
      | "contains"
      | "deleteIdentity"
      | "identity"
      | "identityStorage"
      | "investorCountry"
      | "isVerified"
      | "issuersRegistry"
      | "registerIdentity"
      | "setClaimTopicsRegistry"
      | "setIdentityRegistryStorage"
      | "setTrustedIssuersRegistry"
      | "topicsRegistry"
      | "updateCountry"
      | "updateIdentity"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ClaimTopicsRegistrySet"
      | "CountryUpdated"
      | "IdentityRegistered"
      | "IdentityRemoved"
      | "IdentityStorageSet"
      | "IdentityUpdated"
      | "TrustedIssuersRegistrySet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "batchRegisterIdentity",
    values: [AddressLike[], AddressLike[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "contains",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteIdentity",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "identity",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "identityStorage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "investorCountry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isVerified",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "issuersRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "registerIdentity",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "setClaimTopicsRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setIdentityRegistryStorage",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setTrustedIssuersRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "topicsRegistry",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "updateCountry",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "updateIdentity",
    values: [AddressLike, AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "batchRegisterIdentity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "contains", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "deleteIdentity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "identity", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "identityStorage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "investorCountry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "isVerified", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "issuersRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "registerIdentity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setClaimTopicsRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setIdentityRegistryStorage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setTrustedIssuersRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "topicsRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateCountry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "updateIdentity",
    data: BytesLike
  ): Result;
}

export namespace ClaimTopicsRegistrySetEvent {
  export type InputTuple = [claimTopicsRegistry: AddressLike];
  export type OutputTuple = [claimTopicsRegistry: string];
  export interface OutputObject {
    claimTopicsRegistry: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CountryUpdatedEvent {
  export type InputTuple = [
    investorAddress: AddressLike,
    country: BigNumberish
  ];
  export type OutputTuple = [investorAddress: string, country: bigint];
  export interface OutputObject {
    investorAddress: string;
    country: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdentityRegisteredEvent {
  export type InputTuple = [
    investorAddress: AddressLike,
    identity: AddressLike
  ];
  export type OutputTuple = [investorAddress: string, identity: string];
  export interface OutputObject {
    investorAddress: string;
    identity: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdentityRemovedEvent {
  export type InputTuple = [
    investorAddress: AddressLike,
    identity: AddressLike
  ];
  export type OutputTuple = [investorAddress: string, identity: string];
  export interface OutputObject {
    investorAddress: string;
    identity: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdentityStorageSetEvent {
  export type InputTuple = [identityStorage: AddressLike];
  export type OutputTuple = [identityStorage: string];
  export interface OutputObject {
    identityStorage: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdentityUpdatedEvent {
  export type InputTuple = [oldIdentity: AddressLike, newIdentity: AddressLike];
  export type OutputTuple = [oldIdentity: string, newIdentity: string];
  export interface OutputObject {
    oldIdentity: string;
    newIdentity: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TrustedIssuersRegistrySetEvent {
  export type InputTuple = [trustedIssuersRegistry: AddressLike];
  export type OutputTuple = [trustedIssuersRegistry: string];
  export interface OutputObject {
    trustedIssuersRegistry: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IIdentityRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): IIdentityRegistry;
  waitForDeployment(): Promise<this>;

  interface: IIdentityRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  batchRegisterIdentity: TypedContractMethod<
    [
      _userAddresses: AddressLike[],
      _identities: AddressLike[],
      _countries: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;

  contains: TypedContractMethod<[_userAddress: AddressLike], [boolean], "view">;

  deleteIdentity: TypedContractMethod<
    [_userAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  identity: TypedContractMethod<[_userAddress: AddressLike], [string], "view">;

  identityStorage: TypedContractMethod<[], [string], "view">;

  investorCountry: TypedContractMethod<
    [_userAddress: AddressLike],
    [bigint],
    "view"
  >;

  isVerified: TypedContractMethod<
    [_userAddress: AddressLike],
    [boolean],
    "view"
  >;

  issuersRegistry: TypedContractMethod<[], [string], "view">;

  registerIdentity: TypedContractMethod<
    [_userAddress: AddressLike, _identity: AddressLike, _country: BigNumberish],
    [void],
    "nonpayable"
  >;

  setClaimTopicsRegistry: TypedContractMethod<
    [_claimTopicsRegistry: AddressLike],
    [void],
    "nonpayable"
  >;

  setIdentityRegistryStorage: TypedContractMethod<
    [_identityRegistryStorage: AddressLike],
    [void],
    "nonpayable"
  >;

  setTrustedIssuersRegistry: TypedContractMethod<
    [_trustedIssuersRegistry: AddressLike],
    [void],
    "nonpayable"
  >;

  topicsRegistry: TypedContractMethod<[], [string], "view">;

  updateCountry: TypedContractMethod<
    [_userAddress: AddressLike, _country: BigNumberish],
    [void],
    "nonpayable"
  >;

  updateIdentity: TypedContractMethod<
    [_userAddress: AddressLike, _identity: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "batchRegisterIdentity"
  ): TypedContractMethod<
    [
      _userAddresses: AddressLike[],
      _identities: AddressLike[],
      _countries: BigNumberish[]
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "contains"
  ): TypedContractMethod<[_userAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "deleteIdentity"
  ): TypedContractMethod<[_userAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "identity"
  ): TypedContractMethod<[_userAddress: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "identityStorage"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "investorCountry"
  ): TypedContractMethod<[_userAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isVerified"
  ): TypedContractMethod<[_userAddress: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "issuersRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "registerIdentity"
  ): TypedContractMethod<
    [_userAddress: AddressLike, _identity: AddressLike, _country: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setClaimTopicsRegistry"
  ): TypedContractMethod<
    [_claimTopicsRegistry: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setIdentityRegistryStorage"
  ): TypedContractMethod<
    [_identityRegistryStorage: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setTrustedIssuersRegistry"
  ): TypedContractMethod<
    [_trustedIssuersRegistry: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "topicsRegistry"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "updateCountry"
  ): TypedContractMethod<
    [_userAddress: AddressLike, _country: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "updateIdentity"
  ): TypedContractMethod<
    [_userAddress: AddressLike, _identity: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "ClaimTopicsRegistrySet"
  ): TypedContractEvent<
    ClaimTopicsRegistrySetEvent.InputTuple,
    ClaimTopicsRegistrySetEvent.OutputTuple,
    ClaimTopicsRegistrySetEvent.OutputObject
  >;
  getEvent(
    key: "CountryUpdated"
  ): TypedContractEvent<
    CountryUpdatedEvent.InputTuple,
    CountryUpdatedEvent.OutputTuple,
    CountryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "IdentityRegistered"
  ): TypedContractEvent<
    IdentityRegisteredEvent.InputTuple,
    IdentityRegisteredEvent.OutputTuple,
    IdentityRegisteredEvent.OutputObject
  >;
  getEvent(
    key: "IdentityRemoved"
  ): TypedContractEvent<
    IdentityRemovedEvent.InputTuple,
    IdentityRemovedEvent.OutputTuple,
    IdentityRemovedEvent.OutputObject
  >;
  getEvent(
    key: "IdentityStorageSet"
  ): TypedContractEvent<
    IdentityStorageSetEvent.InputTuple,
    IdentityStorageSetEvent.OutputTuple,
    IdentityStorageSetEvent.OutputObject
  >;
  getEvent(
    key: "IdentityUpdated"
  ): TypedContractEvent<
    IdentityUpdatedEvent.InputTuple,
    IdentityUpdatedEvent.OutputTuple,
    IdentityUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "TrustedIssuersRegistrySet"
  ): TypedContractEvent<
    TrustedIssuersRegistrySetEvent.InputTuple,
    TrustedIssuersRegistrySetEvent.OutputTuple,
    TrustedIssuersRegistrySetEvent.OutputObject
  >;

  filters: {
    "ClaimTopicsRegistrySet(address)": TypedContractEvent<
      ClaimTopicsRegistrySetEvent.InputTuple,
      ClaimTopicsRegistrySetEvent.OutputTuple,
      ClaimTopicsRegistrySetEvent.OutputObject
    >;
    ClaimTopicsRegistrySet: TypedContractEvent<
      ClaimTopicsRegistrySetEvent.InputTuple,
      ClaimTopicsRegistrySetEvent.OutputTuple,
      ClaimTopicsRegistrySetEvent.OutputObject
    >;

    "CountryUpdated(address,uint16)": TypedContractEvent<
      CountryUpdatedEvent.InputTuple,
      CountryUpdatedEvent.OutputTuple,
      CountryUpdatedEvent.OutputObject
    >;
    CountryUpdated: TypedContractEvent<
      CountryUpdatedEvent.InputTuple,
      CountryUpdatedEvent.OutputTuple,
      CountryUpdatedEvent.OutputObject
    >;

    "IdentityRegistered(address,address)": TypedContractEvent<
      IdentityRegisteredEvent.InputTuple,
      IdentityRegisteredEvent.OutputTuple,
      IdentityRegisteredEvent.OutputObject
    >;
    IdentityRegistered: TypedContractEvent<
      IdentityRegisteredEvent.InputTuple,
      IdentityRegisteredEvent.OutputTuple,
      IdentityRegisteredEvent.OutputObject
    >;

    "IdentityRemoved(address,address)": TypedContractEvent<
      IdentityRemovedEvent.InputTuple,
      IdentityRemovedEvent.OutputTuple,
      IdentityRemovedEvent.OutputObject
    >;
    IdentityRemoved: TypedContractEvent<
      IdentityRemovedEvent.InputTuple,
      IdentityRemovedEvent.OutputTuple,
      IdentityRemovedEvent.OutputObject
    >;

    "IdentityStorageSet(address)": TypedContractEvent<
      IdentityStorageSetEvent.InputTuple,
      IdentityStorageSetEvent.OutputTuple,
      IdentityStorageSetEvent.OutputObject
    >;
    IdentityStorageSet: TypedContractEvent<
      IdentityStorageSetEvent.InputTuple,
      IdentityStorageSetEvent.OutputTuple,
      IdentityStorageSetEvent.OutputObject
    >;

    "IdentityUpdated(address,address)": TypedContractEvent<
      IdentityUpdatedEvent.InputTuple,
      IdentityUpdatedEvent.OutputTuple,
      IdentityUpdatedEvent.OutputObject
    >;
    IdentityUpdated: TypedContractEvent<
      IdentityUpdatedEvent.InputTuple,
      IdentityUpdatedEvent.OutputTuple,
      IdentityUpdatedEvent.OutputObject
    >;

    "TrustedIssuersRegistrySet(address)": TypedContractEvent<
      TrustedIssuersRegistrySetEvent.InputTuple,
      TrustedIssuersRegistrySetEvent.OutputTuple,
      TrustedIssuersRegistrySetEvent.OutputObject
    >;
    TrustedIssuersRegistrySet: TypedContractEvent<
      TrustedIssuersRegistrySetEvent.InputTuple,
      TrustedIssuersRegistrySetEvent.OutputTuple,
      TrustedIssuersRegistrySetEvent.OutputObject
    >;
  };
}
