/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../../../common";

export interface IIdentityRegistryStorageInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addIdentityToStorage"
      | "bindIdentityRegistry"
      | "linkedIdentityRegistries"
      | "modifyStoredIdentity"
      | "modifyStoredInvestorCountry"
      | "removeIdentityFromStorage"
      | "storedIdentity"
      | "storedInvestorCountry"
      | "unbindIdentityRegistry"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "CountryModified"
      | "IdentityModified"
      | "IdentityRegistryBound"
      | "IdentityRegistryUnbound"
      | "IdentityStored"
      | "IdentityUnstored"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addIdentityToStorage",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "bindIdentityRegistry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "linkedIdentityRegistries",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "modifyStoredIdentity",
    values: [AddressLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "modifyStoredInvestorCountry",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "removeIdentityFromStorage",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "storedIdentity",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "storedInvestorCountry",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "unbindIdentityRegistry",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addIdentityToStorage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bindIdentityRegistry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "linkedIdentityRegistries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "modifyStoredIdentity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "modifyStoredInvestorCountry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeIdentityFromStorage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storedIdentity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "storedInvestorCountry",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unbindIdentityRegistry",
    data: BytesLike
  ): Result;
}

export namespace CountryModifiedEvent {
  export type InputTuple = [
    investorAddress: AddressLike,
    country: BigNumberish
  ];
  export type OutputTuple = [investorAddress: string, country: bigint];
  export interface OutputObject {
    investorAddress: string;
    country: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdentityModifiedEvent {
  export type InputTuple = [oldIdentity: AddressLike, newIdentity: AddressLike];
  export type OutputTuple = [oldIdentity: string, newIdentity: string];
  export interface OutputObject {
    oldIdentity: string;
    newIdentity: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdentityRegistryBoundEvent {
  export type InputTuple = [identityRegistry: AddressLike];
  export type OutputTuple = [identityRegistry: string];
  export interface OutputObject {
    identityRegistry: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdentityRegistryUnboundEvent {
  export type InputTuple = [identityRegistry: AddressLike];
  export type OutputTuple = [identityRegistry: string];
  export interface OutputObject {
    identityRegistry: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdentityStoredEvent {
  export type InputTuple = [
    investorAddress: AddressLike,
    identity: AddressLike
  ];
  export type OutputTuple = [investorAddress: string, identity: string];
  export interface OutputObject {
    investorAddress: string;
    identity: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdentityUnstoredEvent {
  export type InputTuple = [
    investorAddress: AddressLike,
    identity: AddressLike
  ];
  export type OutputTuple = [investorAddress: string, identity: string];
  export interface OutputObject {
    investorAddress: string;
    identity: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IIdentityRegistryStorage extends BaseContract {
  connect(runner?: ContractRunner | null): IIdentityRegistryStorage;
  waitForDeployment(): Promise<this>;

  interface: IIdentityRegistryStorageInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addIdentityToStorage: TypedContractMethod<
    [_userAddress: AddressLike, _identity: AddressLike, _country: BigNumberish],
    [void],
    "nonpayable"
  >;

  bindIdentityRegistry: TypedContractMethod<
    [_identityRegistry: AddressLike],
    [void],
    "nonpayable"
  >;

  linkedIdentityRegistries: TypedContractMethod<[], [string[]], "view">;

  modifyStoredIdentity: TypedContractMethod<
    [_userAddress: AddressLike, _identity: AddressLike],
    [void],
    "nonpayable"
  >;

  modifyStoredInvestorCountry: TypedContractMethod<
    [_userAddress: AddressLike, _country: BigNumberish],
    [void],
    "nonpayable"
  >;

  removeIdentityFromStorage: TypedContractMethod<
    [_userAddress: AddressLike],
    [void],
    "nonpayable"
  >;

  storedIdentity: TypedContractMethod<
    [_userAddress: AddressLike],
    [string],
    "view"
  >;

  storedInvestorCountry: TypedContractMethod<
    [_userAddress: AddressLike],
    [bigint],
    "view"
  >;

  unbindIdentityRegistry: TypedContractMethod<
    [_identityRegistry: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addIdentityToStorage"
  ): TypedContractMethod<
    [_userAddress: AddressLike, _identity: AddressLike, _country: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "bindIdentityRegistry"
  ): TypedContractMethod<
    [_identityRegistry: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "linkedIdentityRegistries"
  ): TypedContractMethod<[], [string[]], "view">;
  getFunction(
    nameOrSignature: "modifyStoredIdentity"
  ): TypedContractMethod<
    [_userAddress: AddressLike, _identity: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "modifyStoredInvestorCountry"
  ): TypedContractMethod<
    [_userAddress: AddressLike, _country: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeIdentityFromStorage"
  ): TypedContractMethod<[_userAddress: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "storedIdentity"
  ): TypedContractMethod<[_userAddress: AddressLike], [string], "view">;
  getFunction(
    nameOrSignature: "storedInvestorCountry"
  ): TypedContractMethod<[_userAddress: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "unbindIdentityRegistry"
  ): TypedContractMethod<
    [_identityRegistry: AddressLike],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CountryModified"
  ): TypedContractEvent<
    CountryModifiedEvent.InputTuple,
    CountryModifiedEvent.OutputTuple,
    CountryModifiedEvent.OutputObject
  >;
  getEvent(
    key: "IdentityModified"
  ): TypedContractEvent<
    IdentityModifiedEvent.InputTuple,
    IdentityModifiedEvent.OutputTuple,
    IdentityModifiedEvent.OutputObject
  >;
  getEvent(
    key: "IdentityRegistryBound"
  ): TypedContractEvent<
    IdentityRegistryBoundEvent.InputTuple,
    IdentityRegistryBoundEvent.OutputTuple,
    IdentityRegistryBoundEvent.OutputObject
  >;
  getEvent(
    key: "IdentityRegistryUnbound"
  ): TypedContractEvent<
    IdentityRegistryUnboundEvent.InputTuple,
    IdentityRegistryUnboundEvent.OutputTuple,
    IdentityRegistryUnboundEvent.OutputObject
  >;
  getEvent(
    key: "IdentityStored"
  ): TypedContractEvent<
    IdentityStoredEvent.InputTuple,
    IdentityStoredEvent.OutputTuple,
    IdentityStoredEvent.OutputObject
  >;
  getEvent(
    key: "IdentityUnstored"
  ): TypedContractEvent<
    IdentityUnstoredEvent.InputTuple,
    IdentityUnstoredEvent.OutputTuple,
    IdentityUnstoredEvent.OutputObject
  >;

  filters: {
    "CountryModified(address,uint16)": TypedContractEvent<
      CountryModifiedEvent.InputTuple,
      CountryModifiedEvent.OutputTuple,
      CountryModifiedEvent.OutputObject
    >;
    CountryModified: TypedContractEvent<
      CountryModifiedEvent.InputTuple,
      CountryModifiedEvent.OutputTuple,
      CountryModifiedEvent.OutputObject
    >;

    "IdentityModified(address,address)": TypedContractEvent<
      IdentityModifiedEvent.InputTuple,
      IdentityModifiedEvent.OutputTuple,
      IdentityModifiedEvent.OutputObject
    >;
    IdentityModified: TypedContractEvent<
      IdentityModifiedEvent.InputTuple,
      IdentityModifiedEvent.OutputTuple,
      IdentityModifiedEvent.OutputObject
    >;

    "IdentityRegistryBound(address)": TypedContractEvent<
      IdentityRegistryBoundEvent.InputTuple,
      IdentityRegistryBoundEvent.OutputTuple,
      IdentityRegistryBoundEvent.OutputObject
    >;
    IdentityRegistryBound: TypedContractEvent<
      IdentityRegistryBoundEvent.InputTuple,
      IdentityRegistryBoundEvent.OutputTuple,
      IdentityRegistryBoundEvent.OutputObject
    >;

    "IdentityRegistryUnbound(address)": TypedContractEvent<
      IdentityRegistryUnboundEvent.InputTuple,
      IdentityRegistryUnboundEvent.OutputTuple,
      IdentityRegistryUnboundEvent.OutputObject
    >;
    IdentityRegistryUnbound: TypedContractEvent<
      IdentityRegistryUnboundEvent.InputTuple,
      IdentityRegistryUnboundEvent.OutputTuple,
      IdentityRegistryUnboundEvent.OutputObject
    >;

    "IdentityStored(address,address)": TypedContractEvent<
      IdentityStoredEvent.InputTuple,
      IdentityStoredEvent.OutputTuple,
      IdentityStoredEvent.OutputObject
    >;
    IdentityStored: TypedContractEvent<
      IdentityStoredEvent.InputTuple,
      IdentityStoredEvent.OutputTuple,
      IdentityStoredEvent.OutputObject
    >;

    "IdentityUnstored(address,address)": TypedContractEvent<
      IdentityUnstoredEvent.InputTuple,
      IdentityUnstoredEvent.OutputTuple,
      IdentityUnstoredEvent.OutputObject
    >;
    IdentityUnstored: TypedContractEvent<
      IdentityUnstoredEvent.InputTuple,
      IdentityUnstoredEvent.OutputTuple,
      IdentityUnstoredEvent.OutputObject
    >;
  };
}
