/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IReentrancyTarget,
  IReentrancyTargetInterface,
} from "../../../../contracts/mocks/ReentrantERC20.sol/IReentrancyTarget";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "buy",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "token",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
    ],
    name: "redeem",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IReentrancyTarget__factory {
  static readonly abi = _abi;
  static createInterface(): IReentrancyTargetInterface {
    return new Interface(_abi) as IReentrancyTargetInterface;
  }
  static connect(
    address: string,
    runner?: ContractRunner | null
  ): IReentrancyTarget {
    return new Contract(address, _abi, runner) as unknown as IReentrancyTarget;
  }
}
