/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  DeployContractOptions,
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "IModularCompliance",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IModularCompliance__factory>;
    getContractFactory(
      name: "AbstractModule",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.AbstractModule__factory>;
    getContractFactory(
      name: "IModule",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IModule__factory>;
    getContractFactory(
      name: "IClaimTopicsRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IClaimTopicsRegistry__factory>;
    getContractFactory(
      name: "IIdentityRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IIdentityRegistry__factory>;
    getContractFactory(
      name: "IIdentityRegistryStorage",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IIdentityRegistryStorage__factory>;
    getContractFactory(
      name: "ITrustedIssuersRegistry",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ITrustedIssuersRegistry__factory>;
    getContractFactory(
      name: "IToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IToken__factory>;
    getContractFactory(
      name: "IClaimIssuer",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IClaimIssuer__factory>;
    getContractFactory(
      name: "IERC734",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC734__factory>;
    getContractFactory(
      name: "IERC735",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC735__factory>;
    getContractFactory(
      name: "IIdentity",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IIdentity__factory>;
    getContractFactory(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Ownable__factory>;
    getContractFactory(
      name: "Pausable",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Pausable__factory>;
    getContractFactory(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ERC20__factory>;
    getContractFactory(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Metadata__factory>;
    getContractFactory(
      name: "IERC20Permit",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20Permit__factory>;
    getContractFactory(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IERC20__factory>;
    getContractFactory(
      name: "MockERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockERC20__factory>;
    getContractFactory(
      name: "MockTRexToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MockTRexToken__factory>;
    getContractFactory(
      name: "IReentrancyTarget",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IReentrancyTarget__factory>;
    getContractFactory(
      name: "ReentrantERC20",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ReentrantERC20__factory>;
    getContractFactory(
      name: "CountryRestrictModule",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.CountryRestrictModule__factory>;
    getContractFactory(
      name: "MaxBalanceModule",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MaxBalanceModule__factory>;
    getContractFactory(
      name: "MaxInvestorsModule",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MaxInvestorsModule__factory>;
    getContractFactory(
      name: "ITREXToken",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ITREXToken__factory>;
    getContractFactory(
      name: "TREXPlatformController",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.TREXPlatformController__factory>;

    getContractAt(
      name: "IModularCompliance",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IModularCompliance>;
    getContractAt(
      name: "AbstractModule",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.AbstractModule>;
    getContractAt(
      name: "IModule",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IModule>;
    getContractAt(
      name: "IClaimTopicsRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IClaimTopicsRegistry>;
    getContractAt(
      name: "IIdentityRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IIdentityRegistry>;
    getContractAt(
      name: "IIdentityRegistryStorage",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IIdentityRegistryStorage>;
    getContractAt(
      name: "ITrustedIssuersRegistry",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ITrustedIssuersRegistry>;
    getContractAt(
      name: "IToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IToken>;
    getContractAt(
      name: "IClaimIssuer",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IClaimIssuer>;
    getContractAt(
      name: "IERC734",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC734>;
    getContractAt(
      name: "IERC735",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC735>;
    getContractAt(
      name: "IIdentity",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IIdentity>;
    getContractAt(
      name: "Ownable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Ownable>;
    getContractAt(
      name: "Pausable",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.Pausable>;
    getContractAt(
      name: "ERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ERC20>;
    getContractAt(
      name: "IERC20Metadata",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Metadata>;
    getContractAt(
      name: "IERC20Permit",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20Permit>;
    getContractAt(
      name: "IERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IERC20>;
    getContractAt(
      name: "MockERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockERC20>;
    getContractAt(
      name: "MockTRexToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MockTRexToken>;
    getContractAt(
      name: "IReentrancyTarget",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.IReentrancyTarget>;
    getContractAt(
      name: "ReentrantERC20",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ReentrantERC20>;
    getContractAt(
      name: "CountryRestrictModule",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.CountryRestrictModule>;
    getContractAt(
      name: "MaxBalanceModule",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MaxBalanceModule>;
    getContractAt(
      name: "MaxInvestorsModule",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.MaxInvestorsModule>;
    getContractAt(
      name: "ITREXToken",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.ITREXToken>;
    getContractAt(
      name: "TREXPlatformController",
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<Contracts.TREXPlatformController>;

    deployContract(
      name: "IModularCompliance",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IModularCompliance>;
    deployContract(
      name: "AbstractModule",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AbstractModule>;
    deployContract(
      name: "IModule",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IModule>;
    deployContract(
      name: "IClaimTopicsRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IClaimTopicsRegistry>;
    deployContract(
      name: "IIdentityRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IIdentityRegistry>;
    deployContract(
      name: "IIdentityRegistryStorage",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IIdentityRegistryStorage>;
    deployContract(
      name: "ITrustedIssuersRegistry",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ITrustedIssuersRegistry>;
    deployContract(
      name: "IToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IToken>;
    deployContract(
      name: "IClaimIssuer",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IClaimIssuer>;
    deployContract(
      name: "IERC734",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC734>;
    deployContract(
      name: "IERC735",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC735>;
    deployContract(
      name: "IIdentity",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IIdentity>;
    deployContract(
      name: "Ownable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "Pausable",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Pausable>;
    deployContract(
      name: "ERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "IERC20Metadata",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20Permit",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Permit>;
    deployContract(
      name: "IERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "MockERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockERC20>;
    deployContract(
      name: "MockTRexToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockTRexToken>;
    deployContract(
      name: "IReentrancyTarget",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IReentrancyTarget>;
    deployContract(
      name: "ReentrantERC20",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReentrantERC20>;
    deployContract(
      name: "CountryRestrictModule",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CountryRestrictModule>;
    deployContract(
      name: "MaxBalanceModule",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MaxBalanceModule>;
    deployContract(
      name: "MaxInvestorsModule",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MaxInvestorsModule>;
    deployContract(
      name: "ITREXToken",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ITREXToken>;
    deployContract(
      name: "TREXPlatformController",
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TREXPlatformController>;

    deployContract(
      name: "IModularCompliance",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IModularCompliance>;
    deployContract(
      name: "AbstractModule",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.AbstractModule>;
    deployContract(
      name: "IModule",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IModule>;
    deployContract(
      name: "IClaimTopicsRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IClaimTopicsRegistry>;
    deployContract(
      name: "IIdentityRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IIdentityRegistry>;
    deployContract(
      name: "IIdentityRegistryStorage",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IIdentityRegistryStorage>;
    deployContract(
      name: "ITrustedIssuersRegistry",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ITrustedIssuersRegistry>;
    deployContract(
      name: "IToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IToken>;
    deployContract(
      name: "IClaimIssuer",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IClaimIssuer>;
    deployContract(
      name: "IERC734",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC734>;
    deployContract(
      name: "IERC735",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC735>;
    deployContract(
      name: "IIdentity",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IIdentity>;
    deployContract(
      name: "Ownable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Ownable>;
    deployContract(
      name: "Pausable",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.Pausable>;
    deployContract(
      name: "ERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ERC20>;
    deployContract(
      name: "IERC20Metadata",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Metadata>;
    deployContract(
      name: "IERC20Permit",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20Permit>;
    deployContract(
      name: "IERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IERC20>;
    deployContract(
      name: "MockERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockERC20>;
    deployContract(
      name: "MockTRexToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MockTRexToken>;
    deployContract(
      name: "IReentrancyTarget",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.IReentrancyTarget>;
    deployContract(
      name: "ReentrantERC20",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ReentrantERC20>;
    deployContract(
      name: "CountryRestrictModule",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.CountryRestrictModule>;
    deployContract(
      name: "MaxBalanceModule",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MaxBalanceModule>;
    deployContract(
      name: "MaxInvestorsModule",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.MaxInvestorsModule>;
    deployContract(
      name: "ITREXToken",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.ITREXToken>;
    deployContract(
      name: "TREXPlatformController",
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<Contracts.TREXPlatformController>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
