export const ROUTES = Object.freeze({
  root: '/',
  login: '/login',
  signup: '/signup',
  verifyEmail: '/verify-email',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  dashboard: '/app/dashboard',
  marketplace: '/app/marketplace',
  marketplaceToken: (tokenId = ':tokenId') => `/app/marketplace/${tokenId}`,
  applications: '/app/applications',
  assetManagement: '/app/asset-management',
  applicationDetail: (interestUid = ':interestUid') => `/app/applications/${interestUid}`,
  applicationClaim: (interestUid = ':interestUid') => `/app/applications/${interestUid}/submit-claim`,
  purchaseToken: (interestUid = ':interestUid') => `/app/applications/${interestUid}/purchase`,
  sendToken: (interestUid = ':interestUid') => `/app/applications/${interestUid}/send`,
  redeemToken: (interestUid = ':interestUid') => `/app/applications/${interestUid}/redeem`,
  projects: '/app/projects',
  createToken: '/app/tokens/new',
  tokenIssuanceStep: (step = ':step') => `/app/tokens/new/${step}`,
  tokenDeploying: '/app/tokens/new/deploying',
  tokenSuccess: (tokenAddress = ':tokenAddress') => `/app/tokens/${tokenAddress}/success`,
  tokenDetails: (tokenAddress = ':tokenAddress') => `/app/tokens/${tokenAddress}`,
  identity: '/app/identity',
  compliance: '/app/compliance',
  investors: '/app/investors',
  issuerInvestorDirectory: '/app/investor-directory',
  invitations: '/app/invitations',
  portfolio: '/app/portfolio',
  issuerRedemptions: '/app/redemptions',
  issuerRedemption: (redemptionUid = ':redemptionUid') => `/app/redemptions/${redemptionUid}`,
  transactions: '/app/transactions',
  corporateActions: '/app/corporate-actions',
  documents: '/app/documents',
  reports: '/app/reports',
  users: '/app/team',
  profile: '/app/profile',
  settings: '/app/settings',
  adminRoot: '/admin',
  adminDashboard: '/admin/dashboard',
  adminReviewQueue: '/admin/reviews',
  adminOrganizations: '/admin/organizations',
  adminOrganizationReview: (organizationId = ':organizationId') => `/admin/organizations/${organizationId}`,
  adminUsers: '/admin/users',
  adminAuditLogs: '/admin/audit-logs',
  adminSettings: '/admin/settings',
  adminProfile: '/admin/profile',
  adminDocumentation: '/admin/documentation',
  adminSecurityLogs: '/admin/security-logs',
  organization: '/app/organization',
  organizationCompany: '/app/organization/company-information',
  organizationJurisdiction: '/app/organization/jurisdiction',
  organizationUbo: '/app/organization/ubo',
  organizationDocuments: '/app/organization/documents',
  organizationReview: '/app/organization/review',
  organizationPending: '/app/organization/pending',
  organizationRejected: '/app/organization/rejected',
  organizationVerified: '/app/organization/verified',
  organizationOverview: '/app/organization/overview',
  unauthorized: '/unauthorized',
  forbidden: '/forbidden',
  networkError: '/network-error',
  notFound: '*',
});
