/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IdFactoryAccessManagerInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "ADMIN_ROLE"
      | "DEFAULT_ADMIN_ROLE"
      | "IDENTITY_AUTHORIZER_ROLE"
      | "addTokenFactory"
      | "createIdentity"
      | "createIdentityWithManagementKeys"
      | "getRoleAdmin"
      | "grantRole"
      | "hasRole"
      | "idFactory"
      | "idFactoryOwner"
      | "removeTokenFactory"
      | "renounceRole"
      | "revokeRole"
      | "setIdFactory"
      | "supportsInterface"
      | "transferIdFactoryOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "IdFactoryOwnershipTransferred"
      | "IdFactoryUpdated"
      | "IdentityCreated"
      | "IdentityWithKeysCreated"
      | "RoleAdminChanged"
      | "RoleGranted"
      | "RoleRevoked"
      | "TokenFactoryAddedViaRelayer"
      | "TokenFactoryRemovedViaRelayer"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "IDENTITY_AUTHORIZER_ROLE",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "addTokenFactory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createIdentity",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createIdentityWithManagementKeys",
    values: [AddressLike, string, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getRoleAdmin",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "grantRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "hasRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(functionFragment: "idFactory", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "idFactoryOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "removeTokenFactory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "renounceRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "revokeRole",
    values: [BytesLike, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "setIdFactory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "supportsInterface",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "transferIdFactoryOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(functionFragment: "ADMIN_ROLE", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "DEFAULT_ADMIN_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "IDENTITY_AUTHORIZER_ROLE",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "addTokenFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createIdentity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createIdentityWithManagementKeys",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getRoleAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "grantRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "hasRole", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "idFactory", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "idFactoryOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeTokenFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceRole",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "revokeRole", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setIdFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "supportsInterface",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferIdFactoryOwnership",
    data: BytesLike
  ): Result;
}

export namespace IdFactoryOwnershipTransferredEvent {
  export type InputTuple = [caller: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [caller: string, newOwner: string];
  export interface OutputObject {
    caller: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdFactoryUpdatedEvent {
  export type InputTuple = [
    previousFactory: AddressLike,
    newFactory: AddressLike
  ];
  export type OutputTuple = [previousFactory: string, newFactory: string];
  export interface OutputObject {
    previousFactory: string;
    newFactory: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdentityCreatedEvent {
  export type InputTuple = [
    caller: AddressLike,
    wallet: AddressLike,
    salt: string,
    identity: AddressLike
  ];
  export type OutputTuple = [
    caller: string,
    wallet: string,
    salt: string,
    identity: string
  ];
  export interface OutputObject {
    caller: string;
    wallet: string;
    salt: string;
    identity: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace IdentityWithKeysCreatedEvent {
  export type InputTuple = [
    caller: AddressLike,
    wallet: AddressLike,
    salt: string,
    identity: AddressLike
  ];
  export type OutputTuple = [
    caller: string,
    wallet: string,
    salt: string,
    identity: string
  ];
  export interface OutputObject {
    caller: string;
    wallet: string;
    salt: string;
    identity: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleAdminChangedEvent {
  export type InputTuple = [
    role: BytesLike,
    previousAdminRole: BytesLike,
    newAdminRole: BytesLike
  ];
  export type OutputTuple = [
    role: string,
    previousAdminRole: string,
    newAdminRole: string
  ];
  export interface OutputObject {
    role: string;
    previousAdminRole: string;
    newAdminRole: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleGrantedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RoleRevokedEvent {
  export type InputTuple = [
    role: BytesLike,
    account: AddressLike,
    sender: AddressLike
  ];
  export type OutputTuple = [role: string, account: string, sender: string];
  export interface OutputObject {
    role: string;
    account: string;
    sender: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenFactoryAddedViaRelayerEvent {
  export type InputTuple = [caller: AddressLike, factory: AddressLike];
  export type OutputTuple = [caller: string, factory: string];
  export interface OutputObject {
    caller: string;
    factory: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace TokenFactoryRemovedViaRelayerEvent {
  export type InputTuple = [caller: AddressLike, factory: AddressLike];
  export type OutputTuple = [caller: string, factory: string];
  export interface OutputObject {
    caller: string;
    factory: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface IdFactoryAccessManager extends BaseContract {
  connect(runner?: ContractRunner | null): IdFactoryAccessManager;
  waitForDeployment(): Promise<this>;

  interface: IdFactoryAccessManagerInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  DEFAULT_ADMIN_ROLE: TypedContractMethod<[], [string], "view">;

  IDENTITY_AUTHORIZER_ROLE: TypedContractMethod<[], [string], "view">;

  addTokenFactory: TypedContractMethod<
    [_factory: AddressLike],
    [void],
    "nonpayable"
  >;

  createIdentity: TypedContractMethod<
    [_wallet: AddressLike, _salt: string],
    [string],
    "nonpayable"
  >;

  createIdentityWithManagementKeys: TypedContractMethod<
    [_wallet: AddressLike, _salt: string, _managementKeys: BytesLike[]],
    [string],
    "nonpayable"
  >;

  getRoleAdmin: TypedContractMethod<[role: BytesLike], [string], "view">;

  grantRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  hasRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;

  idFactory: TypedContractMethod<[], [string], "view">;

  idFactoryOwner: TypedContractMethod<[], [string], "view">;

  removeTokenFactory: TypedContractMethod<
    [_factory: AddressLike],
    [void],
    "nonpayable"
  >;

  renounceRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  revokeRole: TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;

  setIdFactory: TypedContractMethod<
    [_newFactory: AddressLike],
    [void],
    "nonpayable"
  >;

  supportsInterface: TypedContractMethod<
    [interfaceId: BytesLike],
    [boolean],
    "view"
  >;

  transferIdFactoryOwnership: TypedContractMethod<
    [_newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "DEFAULT_ADMIN_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "IDENTITY_AUTHORIZER_ROLE"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "addTokenFactory"
  ): TypedContractMethod<[_factory: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createIdentity"
  ): TypedContractMethod<
    [_wallet: AddressLike, _salt: string],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createIdentityWithManagementKeys"
  ): TypedContractMethod<
    [_wallet: AddressLike, _salt: string, _managementKeys: BytesLike[]],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "getRoleAdmin"
  ): TypedContractMethod<[role: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "grantRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "hasRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "idFactory"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "idFactoryOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeTokenFactory"
  ): TypedContractMethod<[_factory: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "renounceRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "revokeRole"
  ): TypedContractMethod<
    [role: BytesLike, account: AddressLike],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setIdFactory"
  ): TypedContractMethod<[_newFactory: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "supportsInterface"
  ): TypedContractMethod<[interfaceId: BytesLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "transferIdFactoryOwnership"
  ): TypedContractMethod<[_newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "IdFactoryOwnershipTransferred"
  ): TypedContractEvent<
    IdFactoryOwnershipTransferredEvent.InputTuple,
    IdFactoryOwnershipTransferredEvent.OutputTuple,
    IdFactoryOwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "IdFactoryUpdated"
  ): TypedContractEvent<
    IdFactoryUpdatedEvent.InputTuple,
    IdFactoryUpdatedEvent.OutputTuple,
    IdFactoryUpdatedEvent.OutputObject
  >;
  getEvent(
    key: "IdentityCreated"
  ): TypedContractEvent<
    IdentityCreatedEvent.InputTuple,
    IdentityCreatedEvent.OutputTuple,
    IdentityCreatedEvent.OutputObject
  >;
  getEvent(
    key: "IdentityWithKeysCreated"
  ): TypedContractEvent<
    IdentityWithKeysCreatedEvent.InputTuple,
    IdentityWithKeysCreatedEvent.OutputTuple,
    IdentityWithKeysCreatedEvent.OutputObject
  >;
  getEvent(
    key: "RoleAdminChanged"
  ): TypedContractEvent<
    RoleAdminChangedEvent.InputTuple,
    RoleAdminChangedEvent.OutputTuple,
    RoleAdminChangedEvent.OutputObject
  >;
  getEvent(
    key: "RoleGranted"
  ): TypedContractEvent<
    RoleGrantedEvent.InputTuple,
    RoleGrantedEvent.OutputTuple,
    RoleGrantedEvent.OutputObject
  >;
  getEvent(
    key: "RoleRevoked"
  ): TypedContractEvent<
    RoleRevokedEvent.InputTuple,
    RoleRevokedEvent.OutputTuple,
    RoleRevokedEvent.OutputObject
  >;
  getEvent(
    key: "TokenFactoryAddedViaRelayer"
  ): TypedContractEvent<
    TokenFactoryAddedViaRelayerEvent.InputTuple,
    TokenFactoryAddedViaRelayerEvent.OutputTuple,
    TokenFactoryAddedViaRelayerEvent.OutputObject
  >;
  getEvent(
    key: "TokenFactoryRemovedViaRelayer"
  ): TypedContractEvent<
    TokenFactoryRemovedViaRelayerEvent.InputTuple,
    TokenFactoryRemovedViaRelayerEvent.OutputTuple,
    TokenFactoryRemovedViaRelayerEvent.OutputObject
  >;

  filters: {
    "IdFactoryOwnershipTransferred(address,address)": TypedContractEvent<
      IdFactoryOwnershipTransferredEvent.InputTuple,
      IdFactoryOwnershipTransferredEvent.OutputTuple,
      IdFactoryOwnershipTransferredEvent.OutputObject
    >;
    IdFactoryOwnershipTransferred: TypedContractEvent<
      IdFactoryOwnershipTransferredEvent.InputTuple,
      IdFactoryOwnershipTransferredEvent.OutputTuple,
      IdFactoryOwnershipTransferredEvent.OutputObject
    >;

    "IdFactoryUpdated(address,address)": TypedContractEvent<
      IdFactoryUpdatedEvent.InputTuple,
      IdFactoryUpdatedEvent.OutputTuple,
      IdFactoryUpdatedEvent.OutputObject
    >;
    IdFactoryUpdated: TypedContractEvent<
      IdFactoryUpdatedEvent.InputTuple,
      IdFactoryUpdatedEvent.OutputTuple,
      IdFactoryUpdatedEvent.OutputObject
    >;

    "IdentityCreated(address,address,string,address)": TypedContractEvent<
      IdentityCreatedEvent.InputTuple,
      IdentityCreatedEvent.OutputTuple,
      IdentityCreatedEvent.OutputObject
    >;
    IdentityCreated: TypedContractEvent<
      IdentityCreatedEvent.InputTuple,
      IdentityCreatedEvent.OutputTuple,
      IdentityCreatedEvent.OutputObject
    >;

    "IdentityWithKeysCreated(address,address,string,address)": TypedContractEvent<
      IdentityWithKeysCreatedEvent.InputTuple,
      IdentityWithKeysCreatedEvent.OutputTuple,
      IdentityWithKeysCreatedEvent.OutputObject
    >;
    IdentityWithKeysCreated: TypedContractEvent<
      IdentityWithKeysCreatedEvent.InputTuple,
      IdentityWithKeysCreatedEvent.OutputTuple,
      IdentityWithKeysCreatedEvent.OutputObject
    >;

    "RoleAdminChanged(bytes32,bytes32,bytes32)": TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;
    RoleAdminChanged: TypedContractEvent<
      RoleAdminChangedEvent.InputTuple,
      RoleAdminChangedEvent.OutputTuple,
      RoleAdminChangedEvent.OutputObject
    >;

    "RoleGranted(bytes32,address,address)": TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;
    RoleGranted: TypedContractEvent<
      RoleGrantedEvent.InputTuple,
      RoleGrantedEvent.OutputTuple,
      RoleGrantedEvent.OutputObject
    >;

    "RoleRevoked(bytes32,address,address)": TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;
    RoleRevoked: TypedContractEvent<
      RoleRevokedEvent.InputTuple,
      RoleRevokedEvent.OutputTuple,
      RoleRevokedEvent.OutputObject
    >;

    "TokenFactoryAddedViaRelayer(address,address)": TypedContractEvent<
      TokenFactoryAddedViaRelayerEvent.InputTuple,
      TokenFactoryAddedViaRelayerEvent.OutputTuple,
      TokenFactoryAddedViaRelayerEvent.OutputObject
    >;
    TokenFactoryAddedViaRelayer: TypedContractEvent<
      TokenFactoryAddedViaRelayerEvent.InputTuple,
      TokenFactoryAddedViaRelayerEvent.OutputTuple,
      TokenFactoryAddedViaRelayerEvent.OutputObject
    >;

    "TokenFactoryRemovedViaRelayer(address,address)": TypedContractEvent<
      TokenFactoryRemovedViaRelayerEvent.InputTuple,
      TokenFactoryRemovedViaRelayerEvent.OutputTuple,
      TokenFactoryRemovedViaRelayerEvent.OutputObject
    >;
    TokenFactoryRemovedViaRelayer: TypedContractEvent<
      TokenFactoryRemovedViaRelayerEvent.InputTuple,
      TokenFactoryRemovedViaRelayerEvent.OutputTuple,
      TokenFactoryRemovedViaRelayerEvent.OutputObject
    >;
  };
}
