/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedListener,
  TypedContractMethod,
} from "../../../common";

export interface IIdFactoryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addTokenFactory"
      | "createIdentity"
      | "createIdentityWithManagementKeys"
      | "removeTokenFactory"
  ): FunctionFragment;

  encodeFunctionData(
    functionFragment: "addTokenFactory",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "createIdentity",
    values: [AddressLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "createIdentityWithManagementKeys",
    values: [AddressLike, string, BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "removeTokenFactory",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addTokenFactory",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createIdentity",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "createIdentityWithManagementKeys",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "removeTokenFactory",
    data: BytesLike
  ): Result;
}

export interface IIdFactory extends BaseContract {
  connect(runner?: ContractRunner | null): IIdFactory;
  waitForDeployment(): Promise<this>;

  interface: IIdFactoryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addTokenFactory: TypedContractMethod<
    [_factory: AddressLike],
    [void],
    "nonpayable"
  >;

  createIdentity: TypedContractMethod<
    [_wallet: AddressLike, _salt: string],
    [string],
    "nonpayable"
  >;

  createIdentityWithManagementKeys: TypedContractMethod<
    [_wallet: AddressLike, _salt: string, _managementKeys: BytesLike[]],
    [string],
    "nonpayable"
  >;

  removeTokenFactory: TypedContractMethod<
    [_factory: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addTokenFactory"
  ): TypedContractMethod<[_factory: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "createIdentity"
  ): TypedContractMethod<
    [_wallet: AddressLike, _salt: string],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "createIdentityWithManagementKeys"
  ): TypedContractMethod<
    [_wallet: AddressLike, _salt: string, _managementKeys: BytesLike[]],
    [string],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "removeTokenFactory"
  ): TypedContractMethod<[_factory: AddressLike], [void], "nonpayable">;

  filters: {};
}
