/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ITREXToken__factory } from "./ITREXToken__factory";
export { TREXPlatformController__factory } from "./TREXPlatformController__factory";
