/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  IIdFactory,
  IIdFactoryInterface,
} from "../../../../contracts/platform/IdFactoryAccessManager.sol/IIdFactory";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "_factory",
        type: "address",
      },
    ],
    name: "addTokenFactory",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_wallet",
        type: "address",
      },
      {
        internalType: "string",
        name: "_salt",
        type: "string",
      },
    ],
    name: "createIdentity",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_wallet",
        type: "address",
      },
      {
        internalType: "string",
        name: "_salt",
        type: "string",
      },
      {
        internalType: "bytes32[]",
        name: "_managementKeys",
        type: "bytes32[]",
      },
    ],
    name: "createIdentityWithManagementKeys",
    outputs: [
      {
        internalType: "address",
        name: "",
        type: "address",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "_factory",
        type: "address",
      },
    ],
    name: "removeTokenFactory",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class IIdFactory__factory {
  static readonly abi = _abi;
  static createInterface(): IIdFactoryInterface {
    return new Interface(_abi) as IIdFactoryInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): IIdFactory {
    return new Contract(address, _abi, runner) as unknown as IIdFactory;
  }
}
