/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface CountryRestrictModuleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "addCountryRestriction"
      | "batchRestrictCountries"
      | "bindCompliance"
      | "canComplianceBind"
      | "isComplianceBound"
      | "isCountryRestricted"
      | "isPlugAndPlay"
      | "moduleBurnAction"
      | "moduleCheck"
      | "moduleMintAction"
      | "moduleTransferAction"
      | "name"
      | "removeCountryRestriction"
      | "unbindCompliance"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ComplianceBound"
      | "ComplianceUnbound"
      | "CountryRestricted"
      | "CountryUnrestricted"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "addCountryRestriction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "batchRestrictCountries",
    values: [BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "bindCompliance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "canComplianceBind",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isComplianceBound",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isCountryRestricted",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "isPlugAndPlay",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "moduleBurnAction",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "moduleCheck",
    values: [AddressLike, AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "moduleMintAction",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "moduleTransferAction",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "removeCountryRestriction",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unbindCompliance",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "addCountryRestriction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "batchRestrictCountries",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "bindCompliance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canComplianceBind",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isComplianceBound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isCountryRestricted",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPlugAndPlay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "moduleBurnAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "moduleCheck",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "moduleMintAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "moduleTransferAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "removeCountryRestriction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unbindCompliance",
    data: BytesLike
  ): Result;
}

export namespace ComplianceBoundEvent {
  export type InputTuple = [_compliance: AddressLike];
  export type OutputTuple = [_compliance: string];
  export interface OutputObject {
    _compliance: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComplianceUnboundEvent {
  export type InputTuple = [_compliance: AddressLike];
  export type OutputTuple = [_compliance: string];
  export interface OutputObject {
    _compliance: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CountryRestrictedEvent {
  export type InputTuple = [_compliance: AddressLike, _country: BigNumberish];
  export type OutputTuple = [_compliance: string, _country: bigint];
  export interface OutputObject {
    _compliance: string;
    _country: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace CountryUnrestrictedEvent {
  export type InputTuple = [_compliance: AddressLike, _country: BigNumberish];
  export type OutputTuple = [_compliance: string, _country: bigint];
  export interface OutputObject {
    _compliance: string;
    _country: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CountryRestrictModule extends BaseContract {
  connect(runner?: ContractRunner | null): CountryRestrictModule;
  waitForDeployment(): Promise<this>;

  interface: CountryRestrictModuleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  addCountryRestriction: TypedContractMethod<
    [_country: BigNumberish],
    [void],
    "nonpayable"
  >;

  batchRestrictCountries: TypedContractMethod<
    [_countries: BigNumberish[]],
    [void],
    "nonpayable"
  >;

  bindCompliance: TypedContractMethod<
    [_compliance: AddressLike],
    [void],
    "nonpayable"
  >;

  canComplianceBind: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  isComplianceBound: TypedContractMethod<
    [_compliance: AddressLike],
    [boolean],
    "view"
  >;

  isCountryRestricted: TypedContractMethod<
    [_compliance: AddressLike, _country: BigNumberish],
    [boolean],
    "view"
  >;

  isPlugAndPlay: TypedContractMethod<[], [boolean], "view">;

  moduleBurnAction: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [void],
    "nonpayable"
  >;

  moduleCheck: TypedContractMethod<
    [
      arg0: AddressLike,
      _to: AddressLike,
      arg2: BigNumberish,
      _compliance: AddressLike
    ],
    [boolean],
    "view"
  >;

  moduleMintAction: TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [void],
    "nonpayable"
  >;

  moduleTransferAction: TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish],
    [void],
    "nonpayable"
  >;

  name: TypedContractMethod<[], [string], "view">;

  removeCountryRestriction: TypedContractMethod<
    [_country: BigNumberish],
    [void],
    "nonpayable"
  >;

  unbindCompliance: TypedContractMethod<
    [_compliance: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "addCountryRestriction"
  ): TypedContractMethod<[_country: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "batchRestrictCountries"
  ): TypedContractMethod<[_countries: BigNumberish[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "bindCompliance"
  ): TypedContractMethod<[_compliance: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "canComplianceBind"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isComplianceBound"
  ): TypedContractMethod<[_compliance: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isCountryRestricted"
  ): TypedContractMethod<
    [_compliance: AddressLike, _country: BigNumberish],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "isPlugAndPlay"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "moduleBurnAction"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "moduleCheck"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      _to: AddressLike,
      arg2: BigNumberish,
      _compliance: AddressLike
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "moduleMintAction"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "moduleTransferAction"
  ): TypedContractMethod<
    [arg0: AddressLike, arg1: AddressLike, arg2: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "removeCountryRestriction"
  ): TypedContractMethod<[_country: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unbindCompliance"
  ): TypedContractMethod<[_compliance: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ComplianceBound"
  ): TypedContractEvent<
    ComplianceBoundEvent.InputTuple,
    ComplianceBoundEvent.OutputTuple,
    ComplianceBoundEvent.OutputObject
  >;
  getEvent(
    key: "ComplianceUnbound"
  ): TypedContractEvent<
    ComplianceUnboundEvent.InputTuple,
    ComplianceUnboundEvent.OutputTuple,
    ComplianceUnboundEvent.OutputObject
  >;
  getEvent(
    key: "CountryRestricted"
  ): TypedContractEvent<
    CountryRestrictedEvent.InputTuple,
    CountryRestrictedEvent.OutputTuple,
    CountryRestrictedEvent.OutputObject
  >;
  getEvent(
    key: "CountryUnrestricted"
  ): TypedContractEvent<
    CountryUnrestrictedEvent.InputTuple,
    CountryUnrestrictedEvent.OutputTuple,
    CountryUnrestrictedEvent.OutputObject
  >;

  filters: {
    "ComplianceBound(address)": TypedContractEvent<
      ComplianceBoundEvent.InputTuple,
      ComplianceBoundEvent.OutputTuple,
      ComplianceBoundEvent.OutputObject
    >;
    ComplianceBound: TypedContractEvent<
      ComplianceBoundEvent.InputTuple,
      ComplianceBoundEvent.OutputTuple,
      ComplianceBoundEvent.OutputObject
    >;

    "ComplianceUnbound(address)": TypedContractEvent<
      ComplianceUnboundEvent.InputTuple,
      ComplianceUnboundEvent.OutputTuple,
      ComplianceUnboundEvent.OutputObject
    >;
    ComplianceUnbound: TypedContractEvent<
      ComplianceUnboundEvent.InputTuple,
      ComplianceUnboundEvent.OutputTuple,
      ComplianceUnboundEvent.OutputObject
    >;

    "CountryRestricted(address,uint16)": TypedContractEvent<
      CountryRestrictedEvent.InputTuple,
      CountryRestrictedEvent.OutputTuple,
      CountryRestrictedEvent.OutputObject
    >;
    CountryRestricted: TypedContractEvent<
      CountryRestrictedEvent.InputTuple,
      CountryRestrictedEvent.OutputTuple,
      CountryRestrictedEvent.OutputObject
    >;

    "CountryUnrestricted(address,uint16)": TypedContractEvent<
      CountryUnrestrictedEvent.InputTuple,
      CountryUnrestrictedEvent.OutputTuple,
      CountryUnrestrictedEvent.OutputObject
    >;
    CountryUnrestricted: TypedContractEvent<
      CountryUnrestrictedEvent.InputTuple,
      CountryUnrestrictedEvent.OutputTuple,
      CountryUnrestrictedEvent.OutputObject
    >;
  };
}
