/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../../common";

export interface MaxInvestorsModuleInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "bindCompliance"
      | "canComplianceBind"
      | "getHolderCount"
      | "getMaxInvestors"
      | "isComplianceBound"
      | "isPlugAndPlay"
      | "moduleBurnAction"
      | "moduleCheck"
      | "moduleMintAction"
      | "moduleTransferAction"
      | "name"
      | "setMaxInvestors"
      | "unbindCompliance"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ComplianceBound"
      | "ComplianceUnbound"
      | "MaxInvestorsSet"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "bindCompliance",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "canComplianceBind",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getHolderCount",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "getMaxInvestors",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isComplianceBound",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "isPlugAndPlay",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "moduleBurnAction",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "moduleCheck",
    values: [AddressLike, AddressLike, BigNumberish, AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "moduleMintAction",
    values: [AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "moduleTransferAction",
    values: [AddressLike, AddressLike, BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "name", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "setMaxInvestors",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "unbindCompliance",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "bindCompliance",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "canComplianceBind",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getHolderCount",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getMaxInvestors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isComplianceBound",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "isPlugAndPlay",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "moduleBurnAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "moduleCheck",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "moduleMintAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "moduleTransferAction",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "name", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "setMaxInvestors",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "unbindCompliance",
    data: BytesLike
  ): Result;
}

export namespace ComplianceBoundEvent {
  export type InputTuple = [_compliance: AddressLike];
  export type OutputTuple = [_compliance: string];
  export interface OutputObject {
    _compliance: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ComplianceUnboundEvent {
  export type InputTuple = [_compliance: AddressLike];
  export type OutputTuple = [_compliance: string];
  export interface OutputObject {
    _compliance: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace MaxInvestorsSetEvent {
  export type InputTuple = [_compliance: AddressLike, _max: BigNumberish];
  export type OutputTuple = [_compliance: string, _max: bigint];
  export interface OutputObject {
    _compliance: string;
    _max: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface MaxInvestorsModule extends BaseContract {
  connect(runner?: ContractRunner | null): MaxInvestorsModule;
  waitForDeployment(): Promise<this>;

  interface: MaxInvestorsModuleInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  bindCompliance: TypedContractMethod<
    [_compliance: AddressLike],
    [void],
    "nonpayable"
  >;

  canComplianceBind: TypedContractMethod<
    [arg0: AddressLike],
    [boolean],
    "view"
  >;

  getHolderCount: TypedContractMethod<
    [_compliance: AddressLike],
    [bigint],
    "view"
  >;

  getMaxInvestors: TypedContractMethod<
    [_compliance: AddressLike],
    [bigint],
    "view"
  >;

  isComplianceBound: TypedContractMethod<
    [_compliance: AddressLike],
    [boolean],
    "view"
  >;

  isPlugAndPlay: TypedContractMethod<[], [boolean], "view">;

  moduleBurnAction: TypedContractMethod<
    [_from: AddressLike, arg1: BigNumberish],
    [void],
    "nonpayable"
  >;

  moduleCheck: TypedContractMethod<
    [
      arg0: AddressLike,
      _to: AddressLike,
      arg2: BigNumberish,
      _compliance: AddressLike
    ],
    [boolean],
    "view"
  >;

  moduleMintAction: TypedContractMethod<
    [_to: AddressLike, arg1: BigNumberish],
    [void],
    "nonpayable"
  >;

  moduleTransferAction: TypedContractMethod<
    [_from: AddressLike, _to: AddressLike, arg2: BigNumberish],
    [void],
    "nonpayable"
  >;

  name: TypedContractMethod<[], [string], "view">;

  setMaxInvestors: TypedContractMethod<
    [_max: BigNumberish],
    [void],
    "nonpayable"
  >;

  unbindCompliance: TypedContractMethod<
    [_compliance: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "bindCompliance"
  ): TypedContractMethod<[_compliance: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "canComplianceBind"
  ): TypedContractMethod<[arg0: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "getHolderCount"
  ): TypedContractMethod<[_compliance: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "getMaxInvestors"
  ): TypedContractMethod<[_compliance: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "isComplianceBound"
  ): TypedContractMethod<[_compliance: AddressLike], [boolean], "view">;
  getFunction(
    nameOrSignature: "isPlugAndPlay"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "moduleBurnAction"
  ): TypedContractMethod<
    [_from: AddressLike, arg1: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "moduleCheck"
  ): TypedContractMethod<
    [
      arg0: AddressLike,
      _to: AddressLike,
      arg2: BigNumberish,
      _compliance: AddressLike
    ],
    [boolean],
    "view"
  >;
  getFunction(
    nameOrSignature: "moduleMintAction"
  ): TypedContractMethod<
    [_to: AddressLike, arg1: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "moduleTransferAction"
  ): TypedContractMethod<
    [_from: AddressLike, _to: AddressLike, arg2: BigNumberish],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "name"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "setMaxInvestors"
  ): TypedContractMethod<[_max: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "unbindCompliance"
  ): TypedContractMethod<[_compliance: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ComplianceBound"
  ): TypedContractEvent<
    ComplianceBoundEvent.InputTuple,
    ComplianceBoundEvent.OutputTuple,
    ComplianceBoundEvent.OutputObject
  >;
  getEvent(
    key: "ComplianceUnbound"
  ): TypedContractEvent<
    ComplianceUnboundEvent.InputTuple,
    ComplianceUnboundEvent.OutputTuple,
    ComplianceUnboundEvent.OutputObject
  >;
  getEvent(
    key: "MaxInvestorsSet"
  ): TypedContractEvent<
    MaxInvestorsSetEvent.InputTuple,
    MaxInvestorsSetEvent.OutputTuple,
    MaxInvestorsSetEvent.OutputObject
  >;

  filters: {
    "ComplianceBound(address)": TypedContractEvent<
      ComplianceBoundEvent.InputTuple,
      ComplianceBoundEvent.OutputTuple,
      ComplianceBoundEvent.OutputObject
    >;
    ComplianceBound: TypedContractEvent<
      ComplianceBoundEvent.InputTuple,
      ComplianceBoundEvent.OutputTuple,
      ComplianceBoundEvent.OutputObject
    >;

    "ComplianceUnbound(address)": TypedContractEvent<
      ComplianceUnboundEvent.InputTuple,
      ComplianceUnboundEvent.OutputTuple,
      ComplianceUnboundEvent.OutputObject
    >;
    ComplianceUnbound: TypedContractEvent<
      ComplianceUnboundEvent.InputTuple,
      ComplianceUnboundEvent.OutputTuple,
      ComplianceUnboundEvent.OutputObject
    >;

    "MaxInvestorsSet(address,uint256)": TypedContractEvent<
      MaxInvestorsSetEvent.InputTuple,
      MaxInvestorsSetEvent.OutputTuple,
      MaxInvestorsSetEvent.OutputObject
    >;
    MaxInvestorsSet: TypedContractEvent<
      MaxInvestorsSetEvent.InputTuple,
      MaxInvestorsSetEvent.OutputTuple,
      MaxInvestorsSetEvent.OutputObject
    >;
  };
}
