import { useState } from 'react';
import { BellRing, KeyRound, Save, ShieldCheck, SlidersHorizontal } from 'lucide-react';
import { toast } from 'sonner';
import { AdminPanel } from '@/components/admin/AdminPanel';
import { useDocumentTitle } from '@/hooks/useDocumentTitle';

export default function AdminSettingsPage() {
  useDocumentTitle('Admin Settings');
  const [settings, setSettings] = useState({ dualApproval: true, highRiskThreshold: 60, documentAutoCheck: true, emailDecisions: true, slackEscalations: false });
  const update = (key, value) => setSettings((current) => ({ ...current, [key]: value }));
  return <div className="space-y-6"><header className="flex flex-col gap-4 sm:flex-row sm:items-end sm:justify-between"><div><p className="mb-2 text-[11px] font-semibold tracking-[0.16em] text-blue-600 uppercase dark:text-blue-400">Governance configuration</p><h2 className="m-0 text-3xl font-semibold tracking-normal text-slate-950 sm:text-4xl dark:text-white">Admin Settings</h2><p className="mt-3 mb-0 text-sm leading-6 text-slate-500 dark:text-slate-400">Configure review controls without changing issuer business logic.</p></div><button type="button" onClick={()=>toast.success('Admin settings saved')} className="inline-flex min-h-11 items-center justify-center gap-2 rounded-xl bg-slate-950 px-5 text-sm font-semibold text-white dark:bg-white dark:text-slate-950"><Save className="size-4" />Save settings</button></header>
    <div className="grid gap-6 xl:grid-cols-2"><AdminPanel title="Review policy" description="Decision governance and risk escalation controls."><SettingToggle icon={ShieldCheck} title="Require dual approval for high-risk organizations" text="A second compliance lead must confirm decisions above the risk threshold." checked={settings.dualApproval} onChange={(value)=>update('dualApproval',value)} /><div className="mt-4 rounded-2xl border border-slate-200 p-4 dark:border-slate-800"><div className="flex items-center justify-between gap-3"><div><strong className="text-sm text-slate-950 dark:text-white">High-risk threshold</strong><p className="mt-1 mb-0 text-xs text-slate-500">Applications at or above this score require escalation.</p></div><strong className="text-lg text-rose-600">{settings.highRiskThreshold}</strong></div><input type="range" min="30" max="90" value={settings.highRiskThreshold} onChange={(event)=>update('highRiskThreshold',Number(event.target.value))} className="mt-4 w-full accent-rose-600" /></div><SettingToggle icon={SlidersHorizontal} title="Automatic document authenticity checks" text="Run machine validation immediately after each document upload." checked={settings.documentAutoCheck} onChange={(value)=>update('documentAutoCheck',value)} /></AdminPanel>
      <AdminPanel title="Notifications" description="Decision and escalation delivery preferences."><SettingToggle icon={BellRing} title="Email organization decisions" text="Send approval, rejection, and information-request notifications through the platform service." checked={settings.emailDecisions} onChange={(value)=>update('emailDecisions',value)} /><SettingToggle icon={BellRing} title="Slack risk escalation" text="Notify the compliance operations channel when a high-risk case enters review." checked={settings.slackEscalations} onChange={(value)=>update('slackEscalations',value)} /></AdminPanel>
      <AdminPanel title="Security" description="Privileged administrative access controls."><div className="flex items-start gap-3 rounded-2xl border border-slate-200 p-4 dark:border-slate-800"><span className="grid size-10 place-items-center rounded-xl bg-violet-50 text-violet-700 dark:bg-violet-500/10 dark:text-violet-300"><KeyRound className="size-5" /></span><div><strong className="text-sm text-slate-950 dark:text-white">Multi-factor authentication</strong><p className="mt-1 mb-0 text-xs leading-5 text-slate-500">Require MFA for all admin roles through the configured identity provider.</p><button type="button" className="mt-3 min-h-9 rounded-xl border border-slate-200 px-3 text-xs font-bold text-slate-700 dark:border-slate-700 dark:text-slate-200">Configure identity provider</button></div></div></AdminPanel>
    </div></div>;
}
function SettingToggle({ icon:Icon,title,text,checked,onChange }) { return <label className="mt-4 flex cursor-pointer items-start gap-3 rounded-2xl border border-slate-200 p-4 first:mt-0 dark:border-slate-800"><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-blue-50 text-blue-700 dark:bg-blue-500/10 dark:text-blue-300"><Icon className="size-5" /></span><span className="min-w-0 flex-1"><strong className="block text-sm text-slate-950 dark:text-white">{title}</strong><span className="mt-1 block text-xs leading-5 text-slate-500">{text}</span></span><input type="checkbox" checked={checked} onChange={(event)=>onChange(event.target.checked)} className="mt-1 size-5 accent-blue-600" /></label>; }
