/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as trexPlatformControllerSol from "./TREXPlatformController.sol";
export type { trexPlatformControllerSol };
